### ISSUE TITLE
Chapter 12 Table 12.1  - Rounding Issue

### ISSUE THREAD

**Issue by rynmccrmck** [statsthinking21/statsthinking21-core#7]
I can't replicate this locally with knitr (I get 33.33 for nullExpectation) but the book site has a confusing rounding (below).  Not really a big deal but took me a second glance. 

[From the book site:](https://statsthinking21.github.io/statsthinking21-core-site/modeling-categorical-relationships.html#chi-squared-test)
![image](https://user-images.githubusercontent.com/5178938/100012191-dd8db100-2da0-11eb-924a-5a103ea58c02.png)

Amazing book and collection of further readings - thank you for putting this online.

**Comment by poldrack** [comment]
thanks, fixed!
